import { Employee, Department } from '../../types';
import { generateId } from './helpers';

export const mockDepartments: Department[] = [
  {
    id: generateId(),
    name: 'Engineering',
    description: 'Software development and technical operations',
    manager: null,
    employeeCount: 12,
  },
  {
    id: generateId(),
    name: 'Marketing',
    description: 'Brand management and market strategy',
    manager: null,
    employeeCount: 8,
  },
  {
    id: generateId(),
    name: 'Human Resources',
    description: 'Employee relations and recruitment',
    manager: null,
    employeeCount: 5,
  },
  {
    id: generateId(),
    name: 'Finance',
    description: 'Financial planning and accounting',
    manager: null,
    employeeCount: 6,
  },
  {
    id: generateId(),
    name: 'Sales',
    description: 'Revenue generation and customer relationships',
    manager: null,
    employeeCount: 10,
  },
];

export const mockEmployees: Employee[] = [
  {
    id: generateId(),
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@company.com',
    phone: '(555) 123-4567',
    position: 'Senior Developer',
    department: 'Engineering',
    hireDate: '2020-06-15',
    salary: 95000,
    status: 'active',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@company.com',
    phone: '(555) 987-6543',
    position: 'Marketing Manager',
    department: 'Marketing',
    hireDate: '2019-03-10',
    salary: 85000,
    status: 'active',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@company.com',
    phone: '(555) 456-7890',
    position: 'HR Specialist',
    department: 'Human Resources',
    hireDate: '2021-01-20',
    salary: 65000,
    status: 'active',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'Emily',
    lastName: 'Williams',
    email: 'emily.williams@company.com',
    phone: '(555) 234-5678',
    position: 'Financial Analyst',
    department: 'Finance',
    hireDate: '2022-04-05',
    salary: 72000,
    status: 'active',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@company.com',
    phone: '(555) 876-5432',
    position: 'Sales Representative',
    department: 'Sales',
    hireDate: '2020-09-12',
    salary: 68000,
    status: 'on leave',
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'Sarah',
    lastName: 'Davis',
    email: 'sarah.davis@company.com',
    phone: '(555) 345-6789',
    position: 'Product Manager',
    department: 'Engineering',
    hireDate: '2021-07-30',
    salary: 90000,
    status: 'active',
    avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'Robert',
    lastName: 'Miller',
    email: 'robert.miller@company.com',
    phone: '(555) 789-0123',
    position: 'Content Strategist',
    department: 'Marketing',
    hireDate: '2022-01-15',
    salary: 67000,
    status: 'inactive',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: generateId(),
    firstName: 'Jennifer',
    lastName: 'Wilson',
    email: 'jennifer.wilson@company.com',
    phone: '(555) 567-8901',
    position: 'Frontend Developer',
    department: 'Engineering',
    hireDate: '2022-06-10',
    salary: 78000,
    status: 'active',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
];